services:
  db:
    container_name: postgre_database
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
     - ./postgres/:/var/lib/postgresql
    environment:
     - POSTGRES_PASSWORD=123456
    
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:9.5.0
    user: '${UID}:${GID}'
    ports:
      - '5050:80'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=superman@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
